export const CONFIGURATION_RESET_STATE = 'CONFIGURATION_RESET_STATE';
export const CONFIGURATION_CURRENT_ITEM = 'CONFIGURATION_CURRENT_ITEM';

export const CONFIGURATION_REQUEST_LOADING = 'CONFIGURATION_REQUEST_LOADING';
export const CONFIGURATION_REQUEST_SUCCESS = 'CONFIGURATION_REQUEST_SUCCESS';
export const CONFIGURATION_REQUEST_FAILED = 'CONFIGURATION_REQUEST_FAILED';

export const CONFIGURATION_CURRENT_ACTION = 'CONFIGURATION_CURRENT_ACTION';
export const CONFIGURATION_RESET_ACTION = 'CONFIGURATION_RESET_ACTION';
